### ISSUE TITLE
GUI hangs if a user doesn't add Python executable to path

### ISSUE THREAD

**Issue by bzindovic** [ljubicicrobert/SSIMS#1]
SSIMS frontend (GUI) hangs if a user doesn't add Python executable to path. Steps to reproduce:

- check that `python.exe` is not in your `PATH` environment variable
- start the front-end app (from the following location `gui\SSIM Stabilization GUI.exe`)
- app displays a warning message "Could not find python (version 3+) in %PATH%!..."
- click "Ok" button to close previous message
- app opens `"Environment Variables"` system dialog
- click "Cancel" button to cancel adding `python.exe` to `PATH` variable

After this, frontend can be closed through Task Manager only.

**Comment by ljubicicrobert** [comment]
Fixed in release v0.3.0.1. Form now freezes all controls if Python not in %PATH% except topbar and Help button.
